<?xml version="1.0"?>
<package format="3">
  <name>cc_systemlib</name>
  <version>1.0.0</version>
  <description>Companion Computer systemlib (mavlink_log)</description>
  <maintainer email="dev@thaco.local">THACO</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>cc_msgs</depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
