# cmake/cc_module.cmake - PX4-aligned module and test helpers for Companion Computer
# (spec 2026-10-04 §5.11)

include(CMakeParseArguments)

# cc_add_library(NAME <name> SRCS <srcs...> [DEPENDS <deps...>])
function(cc_add_library)
    cmake_parse_arguments(CC "" "NAME" "SRCS;DEPENDS" ${ARGN})
    if(NOT CC_NAME)
        message(FATAL_ERROR "cc_add_library: NAME is required")
    endif()
    add_library(${CC_NAME} STATIC ${CC_SRCS})
    if(CC_DEPENDS)
        target_link_libraries(${CC_NAME} PUBLIC ${CC_DEPENDS})
    endif()
endfunction()

# cc_add_module(MODULE <name> SRCS <srcs...> [DEPENDS <deps...>])
function(cc_add_module)
    cmake_parse_arguments(CC "" "MODULE" "SRCS;DEPENDS" ${ARGN})
    if(NOT CC_MODULE)
        message(FATAL_ERROR "cc_add_module: MODULE is required")
    endif()
    add_library(${CC_MODULE} STATIC ${CC_SRCS})
    if(CC_DEPENDS)
        target_link_libraries(${CC_MODULE} PUBLIC ${CC_DEPENDS})
    endif()
endfunction()

# cc_add_unit_gtest(SRC <src> [LINKLIBS <libs...>] [EXTRA_SRCS <srcs...>])
function(cc_add_unit_gtest)
    if(NOT BUILD_TESTING)
        return()
    endif()

    cmake_parse_arguments(CC "" "SRC" "LINKLIBS;EXTRA_SRCS" ${ARGN})
    if(NOT CC_SRC)
        message(FATAL_ERROR "cc_add_unit_gtest: SRC is required")
    endif()

    get_filename_component(TESTNAME ${CC_SRC} NAME_WE)
    string(REGEX REPLACE "Test$" "" TESTNAME ${TESTNAME})
    set(TEST_TARGET "unit_${TESTNAME}")

    find_package(ament_cmake_gtest QUIET)
    if(ament_cmake_gtest_FOUND)
        ament_add_gtest(${TEST_TARGET} ${CC_SRC} ${CC_EXTRA_SRCS})
        if(CC_LINKLIBS)
            target_link_libraries(${TEST_TARGET} ${CC_LINKLIBS})
        endif()
    else()
        find_package(GTest REQUIRED)
        add_executable(${TEST_TARGET} ${CC_SRC} ${CC_EXTRA_SRCS})
        target_link_libraries(${TEST_TARGET} PRIVATE GTest::gtest GTest::gtest_main ${CC_LINKLIBS} pthread)
        include(GoogleTest)
        gtest_discover_tests(${TEST_TARGET})
    endif()
endfunction()
